server:
  port: 8760

eureka:
  instance:
    hostname: localhost2
    prefer-ip-address: true   #访问路径可以显示IP地址
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost3:8759/eureka/,http://localhost:8761/eureka/
spring:
  application:
    name: eureka-server