server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true   #访问路径可以显示IP地址
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost2:8760/eureka/,http://localhost3:8759/eureka/
spring:
  application:
    name: eureka-server