
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8760/eureka/,http://localhost:8759/eureka/
server:
  port: 8762
spring:
  application:
    name: service-hi

